### PR TITLE
Add Pong

### PR DESCRIPTION
**Pull request by drpaneas**
Add my game remake of pong using Ebiten engine

### CODE REVIEW

**Comment by sedyh** [comment]
Hello, sorry for the long delay.
Well documented.

Could you please fix the following:

- Maybe it's better to ignore whole [.idea/](https://github.com/drpaneas/pong/tree/master/.idea) instead of specific files?
Inside one team, it probably makes sense to fumble non-user-specific settings, but in the open source everyone has their own editor and it seems that this will only interfere.

- Different receiver names:
```go
func (p *Player) GetPaddle() *Paddle {...}
func (player *Player) Draw(screen *ebiten.Image) {...}
func (player *Player) Update() {...}
```

- I don't think parentheses are needed.
```go
// setInitialVelocity reduces the ball speed
// handleFirstService handles the first service of the game
// handleScore handles the scoring of the game
// bounce() is making the ball bounce on the enemy paddle
// patrol() is making the enemy paddle go randomly up and down
```

- Maybe it worth to separate `wasm/` and `assets/` files into separate packages?

- Game screenshot in README.md if possible.

**Comment by drpaneas** [comment]
Hey there, thanks, I will address all of them. Thanks for the review :D

**Comment by drpaneas** [comment]
@sedyh I've addressed all of your comment and I've also resolved the issue you opened that was related to Firefox's second canvas. PTAL ;)

**Comment by sedyh** [comment]
Nice. Please also fix the name in about section and it seems to be done:
image

**Comment by sedyh** [comment]
Nice. Added.

**Pull request merged**
