### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by mcarpenter622**
Update ebitenui (It is now maintained by me and its URL has been upda…ted)

Add ebitengine-input library.

### CODE REVIEW

**Comment by mcarpenter622** [comment]
This includes the library in Issue #12

**Comment by sedyh** [comment]
Hello, thanks for PR.
The author of ebitengine-input asked to wait until tomorrow while he prepares the library for release.

**Comment by mcarpenter622** [comment]
Thats great! =) I can modify the PR if you'd prefer to have that be separate or just leave it as is?

**Comment by sedyh** [comment]
If it will be separate I can merge it now.
If we leave it as is, I can merge it when the other author will be ready (i.e. probably tomorrow).

**Comment by mcarpenter622** [comment]
Let's leave it then. I am not in any rush if you're not!

Mark

**Pull request merged**
